{
  "hash": "35cdec25287df813616d614e03824f34",
  "result": {
    "markdown": "---\ntitle: \"A Replication of Karlan and List (2007)\"\nauthor: \"Charlotte Hunter\"\ndate: today\ncallout-appearance: minimal # this hides the blue \"i\" icon on .callout-notes\n---\n\n\n## Introduction\n\nDean Karlan at Yale and John List at the University of Chicago conducted a field experiment to test the effectiveness of different fundraising letters. They sent out 50,000 fundraising letters to potential donors, randomly assigning each letter to one of three treatments: a standard letter, a matching grant letter, or a challenge grant letter. They published the results of this experiment in the _American Economic Review_ in 2007. The article and supporting data are available from the [AEA website](https://www.aeaweb.org/articles?id=10.1257/aer.97.5.1774) and from Innovations for Poverty Action as part of [Harvard's Dataverse](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/27853&version=4.2).\n\nIn the experiment, Karlan and List partnered with a nonprofit organization to explore how different types of donation appeals affect giving behavior. While all recipients were previous donors, the letters varied in key ways: some offered no incentive, while others included matching grants of $1:$1, $2:$1, or $3:$1, where a “leadership donor” pledged to match donations up to a certain amount. The letters also varied the suggested contribution amount and the cap on how much the leadership donor would match.\n\nBy randomly assigning these conditions and tracking donations in response, the researchers were able to estimate how changes in perceived “price” and framing influenced both the probability of donating and the total amount given. This project seeks to replicate their findings using the original data and statistical approach.\n\nThis project seeks to replicate their results.\n\n## Data\n\n### Description\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load libraries\nlibrary(haven)\nlibrary(dplyr)\n\ndf <- read_dta(\"~/Desktop/karlan_list_2007.dta\")\n```\n:::\n\n\nThe dataset karlan_list_2007.dta captures the results of a large-scale field experiment on charitable giving, involving 50,083 previous donors to a nonprofit organization. Each row in the dataset represents one individual who received a fundraising letter during the campaign. The experimental design randomly assigned participants to a control group or to one of several treatment groups, which varied along three key dimensions: the match ratio offered (1:1, 2:1, or 3:1), the maximum size of the matching grant ($25,000, $50,000, $100,000, or unstated), and the suggested donation amount (based on prior giving history, scaled by 1.0, 1.25, or 1.5). The dataset records whether the individual made a donation (gave) and how much they donated (amount). It also contains detailed prior giving history, including the number of past donations, recency of giving, and highest previous contribution. Demographic information is included at the zip-code level, such as racial composition (pwhite, pblack), median household income, average household size, homeownership rates, and educational attainment. Additionally, political context is captured through indicators for whether the individual lived in a red or blue state or county during the 2004 presidential election. This rich set of variables enables analysis not only of overall treatment effects but also of heterogeneous effects across political and demographic subgroups.\n\n:::: {.callout-note collapse=\"true\"}\n### Variable Definitions\n\n| Variable             | Description                                                         |\n|----------------------|---------------------------------------------------------------------|\n| `treatment`          | Treatment                                                           |\n| `control`            | Control                                                             |\n| `ratio`              | Match ratio                                                         |\n| `ratio2`             | 2:1 match ratio                                                     |\n| `ratio3`             | 3:1 match ratio                                                     |\n| `size`               | Match threshold                                                     |\n| `size25`             | \\$25,000 match threshold                                            |\n| `size50`             | \\$50,000 match threshold                                            |\n| `size100`            | \\$100,000 match threshold                                           |\n| `sizeno`             | Unstated match threshold                                            |\n| `ask`                | Suggested donation amount                                           |\n| `askd1`              | Suggested donation was highest previous contribution                |\n| `askd2`              | Suggested donation was 1.25 x highest previous contribution         |\n| `askd3`              | Suggested donation was 1.50 x highest previous contribution         |\n| `ask1`               | Highest previous contribution (for suggestion)                      |\n| `ask2`               | 1.25 x highest previous contribution (for suggestion)               |\n| `ask3`               | 1.50 x highest previous contribution (for suggestion)               |\n| `amount`             | Dollars given                                                       |\n| `gave`               | Gave anything                                                       |\n| `amountchange`       | Change in amount given                                              |\n| `hpa`                | Highest previous contribution                                       |\n| `ltmedmra`           | Small prior donor: last gift was less than median \\$35              |\n| `freq`               | Number of prior donations                                           |\n| `years`              | Number of years since initial donation                              |\n| `year5`              | At least 5 years since initial donation                             |\n| `mrm2`               | Number of months since last donation                                |\n| `dormant`            | Already donated in 2005                                             |\n| `female`             | Female                                                              |\n| `couple`             | Couple                                                              |\n| `state50one`         | State tag: 1 for one observation of each of 50 states; 0 otherwise  |\n| `nonlit`             | Nonlitigation                                                       |\n| `cases`              | Court cases from state in 2004-5 in which organization was involved |\n| `statecnt`           | Percent of sample from state                                        |\n| `stateresponse`      | Proportion of sample from the state who gave                        |\n| `stateresponset`     | Proportion of treated sample from the state who gave                |\n| `stateresponsec`     | Proportion of control sample from the state who gave                |\n| `stateresponsetminc` | stateresponset - stateresponsec                                     |\n| `perbush`            | State vote share for Bush                                           |\n| `close25`            | State vote share for Bush between 47.5% and 52.5%                   |\n| `red0`               | Red state                                                           |\n| `blue0`              | Blue state                                                          |\n| `redcty`             | Red county                                                          |\n| `bluecty`            | Blue county                                                         |\n| `pwhite`             | Proportion white within zip code                                    |\n| `pblack`             | Proportion black within zip code                                    |\n| `page18_39`          | Proportion age 18-39 within zip code                                |\n| `ave_hh_sz`          | Average household size within zip code                              |\n| `median_hhincome`    | Median household income within zip code                             |\n| `powner`             | Proportion house owner within zip code                              |\n| `psch_atlstba`       | Proportion who finished college within zip code                     |\n| `pop_propurban`      | Proportion of population urban within zip code                      |\n\n::::\n\n\n### Balance Test \n\nAs an ad hoc test of the randomization mechanism, I provide a series of tests that compare aspects of the treatment and control groups to assess whether they are statistically significantly different from one another.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ========== mrm2 ==========\ncat(\"### Linear Regression: mrm2 ~ treatment\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n### Linear Regression: mrm2 ~ treatment\n```\n:::\n\n```{.r .cell-code}\nmodel_mrm2 <- lm(mrm2 ~ treatment, data = df)\nprintCoefmat(summary(model_mrm2)$coefficients, signif.stars = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             Estimate Std. Error  t value Pr(>|t|)    \n(Intercept) 12.998142   0.093526 138.9789   <2e-16 ***\ntreatment    0.013686   0.114534   0.1195   0.9049    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\n# ========== female ==========\ncat(\"### Linear Regression: female ~ treatment\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n### Linear Regression: female ~ treatment\n```\n:::\n\n```{.r .cell-code}\nmodel_female <- lm(female ~ treatment, data = df)\nprintCoefmat(summary(model_female)$coefficients, signif.stars = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.2826978  0.0035036 80.6879  < 2e-16 ***\ntreatment   -0.0075469  0.0042920 -1.7584  0.07869 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\n# ========== years ==========\ncat(\"### Linear Regression: years ~ treatment\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n### Linear Regression: years ~ treatment\n```\n:::\n\n```{.r .cell-code}\nmodel_years <- lm(years ~ treatment, data = df)\nprintCoefmat(summary(model_years)$coefficients, signif.stars = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  6.135914   0.042604 144.023   <2e-16 ***\ntreatment   -0.057549   0.052173  -1.103     0.27    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nTo test whether the treatment and control groups were balanced before the experiment began, I ran both a t-test and a linear regression using the variable mrm2, which represents months since last donation. The t-test yielded a t-statistic of approximately 0.12, indicating no statistically significant difference between the groups. I then ran a linear regression of mrm2 on the treatment variable. The coefficient on treatment was nearly zero and not statistically significant, confirming the same result: the groups were balanced. This matches the purpose of Table 1 in the paper, which is to verify that the randomization was successful and that the treatment groups were similar before the intervention. This helps isolate the causal effect of the fundraising treatments observed later in the study.\n\n## Experimental Results\n\n### Charitable Contribution Made\n\nFirst, I analyze whether matched donations lead to an increased response rate of making a donation. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# summary table\nlibrary(ggplot2)\nlibrary(dplyr)\ndonation_rates <- df %>%\n  group_by(treatment) %>%\n  summarise(proportion_donated = mean(gave, na.rm = TRUE)) %>%\n  mutate(group = ifelse(treatment == 1, \"Treatment\", \"Control\"))\n\n# plot\nggplot(donation_rates, aes(x = group, y = proportion_donated)) +\n  geom_bar(stat = \"identity\", fill = \"steelblue\") +\n  labs(\n    title = \"Proportion of People Who Donated\",\n    x = \"\",\n    y = \"Proportion Donated\"\n  ) +\n  scale_y_continuous(\n    breaks = seq(0, 0.03, by = 0.005),\n    limits = c(0, max(donation_rates$proportion_donated) + 0.005)\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThis bar plot shows the proportion of people who donated in each group. The treatment group, which received a fundraising letter mentioning a matching donation, had a slightly higher donation rate than the control group. While both rates are low overall, the visual difference suggests that even a small change in how the request was framed — in this case, offering a match — may have encouraged more people to give.\n\n\n\n```{.r .cell-code}\n# --- Manual t-test ---\ngave_treat <- df$gave[df$treatment == 1]\ngave_control <- df$gave[df$treatment == 0]\n\nmean_treat <- mean(gave_treat, na.rm = TRUE)\nmean_control <- mean(gave_control, na.rm = TRUE)\n\nvar_treat <- mean_treat * (1 - mean_treat)\nvar_control <- mean_control * (1 - mean_control)\n\nn_treat <- sum(!is.na(gave_treat))\nn_control <- sum(!is.na(gave_control))\n\nt_stat <- (mean_treat - mean_control) / sqrt((var_treat / n_treat) + (var_control / n_control))\np_value <- 2 * pt(-abs(t_stat), df = min(n_treat, n_control) - 1)\n```\n\nCalculated t-statistic: 3.2095 \n\np-value:    0.0013 \n\nLinear Regression: gave ~ treatment\n\n```\n             Estimate Std. Error t value  Pr(>|t|)    \n(Intercept) 0.0178582  0.0011007 16.2246 < 2.2e-16 ***\ntreatment   0.0041804  0.0013479  3.1014  0.001927 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\nI compared the proportion of people who donated in the treatment and control groups. In the control group, about 1.8% of individuals donated, compared to 2.2% in the treatment group. Although this seems like a small difference, a statistical test showed that it is highly unlikely to have occurred by chance. I confirmed this result using both a t-test (following the class formula) and a simple linear regression. Both methods showed the same result — that people who received a matching grant letter were significantly more likely to give.\n\nThis tells us something important about human behavior: even a small change in how a request is framed — like offering to match someone’s donation — can meaningfully affect whether they decide to act. The offer likely made giving feel more impactful or urgent. This kind of result is exactly what Table 2A in the paper is highlighting: how relatively subtle changes in message framing can lead to statistically and practically meaningful behavior change.\n\n\nProbit Regression: gave ~ treatment\n\n```\n             Estimate Std. Error z value  Pr(>|z|)    \n(Intercept) -2.100141   0.023316 -90.074 < 2.2e-16 ***\ntreatment    0.086785   0.027878   3.113  0.001852 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\nI ran a probit regression where the outcome variable was whether an individual donated (gave) and the explanatory variable was whether they were assigned to a treatment group (treatment). The coefficient on treatment was small but positive and statistically significant, replicating the result shown in Table 3, Column 1 of the Karlan & List paper. This suggests that receiving a letter with a matching grant offer had a statistically significant effect on the probability of donating, even after accounting for the binary nature of the outcome variable using a probit model.\n\n### Differences between Match Rates\n\nNext, I assess the effectiveness of different sizes of matched donations on the response rate.\n\n\n\n```{.r .cell-code}\n# Filter to match groups\nmatch_data <- df %>% filter(ratio %in% c(\"1\", \"2\", \"3\"))\n\n# 2:1 vs 1:1\nmatch_1v2 <- match_data %>% filter(ratio %in% c(\"1\", \"2\"))\ntt_1v2 <- t.test(gave ~ ratio, data = match_1v2)\n\n# 3:1 vs 1:1\nmatch_1v3 <- match_data %>% filter(ratio %in% c(\"1\", \"3\"))\ntt_1v3 <- t.test(gave ~ ratio, data = match_1v3)\n\n# 3:1 vs 2:1\nmatch_2v3 <- match_data %>% filter(ratio %in% c(\"2\", \"3\"))\ntt_2v3 <- t.test(gave ~ ratio, data = match_2v3)\n```\n\n```\n2:1 vs 1:1\n  t-statistic:  -0.965 \n  p-value:      0.3345 \n\n3:1 vs 1:1\n  t-statistic:  -1.015 \n  p-value:      0.3101 \n\n3:1 vs 2:1\n  t-statistic:  -0.0501 \n  p-value:      0.96 \n```\n\n\nTo test whether larger match ratios increase the likelihood of donating, I ran a series of t-tests comparing donation rates between the 1:1, 2:1, and 3:1 match groups. The results showed no statistically significant differences. The 2:1 and 3:1 groups had slightly higher donation rates than the 1:1 group (about 2.27% vs. 2.07%), but these differences were small and not statistically meaningful (p-values > 0.30). A comparison between the 2:1 and 3:1 groups yielded almost identical results, with a p-value of 0.96. These findings support the authors' claim on page 8 that increasing the match ratio beyond 1:1 does not further increase giving. This suggests that the presence of a match may be what matters most — once donors see their contribution will be matched, making the match larger does not add much persuasive power.\n\n\nLinear Regression: gave ~ ratio\n\n```\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.0207491  0.0013914 14.9122   <2e-16 ***\nratio2      0.0018843  0.0019677  0.9576   0.3383    \nratio3      0.0019843  0.0019679  1.0083   0.3133    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\nIn the regression model comparing match ratios, the 1:1 match group had a baseline donation rate of approximately 2.07%. The 2:1 and 3:1 match groups showed slightly higher estimated donation rates—about 0.19 and 0.20 percentage points more, respectively—but these differences were not statistically significant. Both coefficients had relatively large standard errors and high p-values (above 0.3), indicating low statistical precision. This means we cannot confidently say that higher match ratios had any real effect beyond the 1:1 match. These results support the conclusion that increasing the match ratio does not significantly influence the likelihood of donating.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# mean donation rates\nmeans_by_ratio <- match_data %>%\n  group_by(ratio) %>%\n  summarise(response_rate = mean(gave, na.rm = TRUE))\nmeans_by_ratio\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 2\n  ratio response_rate\n  <fct>         <dbl>\n1 1            0.0207\n2 2            0.0226\n3 3            0.0227\n```\n:::\n:::\n\n\n```{.r .cell-code}\n# 2:1 to 1:1\ndiff_2v1 <- means_by_ratio$response_rate[means_by_ratio$ratio == \"2\"] -\n            means_by_ratio$response_rate[means_by_ratio$ratio == \"1\"]\n\n# 3:1 to 2:1\ndiff_3v2 <- means_by_ratio$response_rate[means_by_ratio$ratio == \"3\"] -\n            means_by_ratio$response_rate[means_by_ratio$ratio == \"2\"]\n```\n\nLinear Regression: gave ~ ratio\n\n```\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.0207491  0.0013914 14.9122   <2e-16 ***\nratio2      0.0018843  0.0019677  0.9576   0.3383    \nratio3      0.0019843  0.0019679  1.0083   0.3133    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\nI calculated the difference in response rates between the 1:1 and 2:1 match groups, and between the 2:1 and 3:1 groups, both directly from the data and using the coefficients from a linear regression. In both cases, the differences were very small—around 0.19 percentage points for 2:1 vs. 1:1, and essentially zero for 3:1 vs. 2:1. These results suggest that increasing the size of the matching donation beyond 1:1 has minimal to no effect on whether people choose to give. The consistency between the raw data and regression confirms that larger match ratios do not meaningfully improve donation rates, reinforcing the idea that simply offering a match may matter more than how generous the match actually is.\n\n### Size of Charitable Contribution\n\nIn this subsection, I analyze the effect of the size of matched donation on the size of the charitable contribution.\n\n\n\n```{.r .cell-code}\n# Filter to donors only (amount is 0 when no donation was made)\ndonors_only <- df %>% filter(gave == 1)\n\n# Manual t-test\nt_test_amount <- t.test(amount ~ treatment, data = donors_only)\n```\n\nLinear Regression: amount ~ treatment (conditional on gave == 1)\n\n```\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  45.5403     2.4234 18.7921   <2e-16 ***\ntreatment    -1.6684     2.8724 -0.5808   0.5615    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\nCalculated t-statistic: 0.5846 \n```\np-value:  0.559 \n```\n\n\nThis analysis shows that, although people in the treatment group were more likely to donate (as shown earlier), those who did donate did not give more than donors in the control group. In fact, if anything, they gave slightly less — but this difference is small and not statistically meaningful.\nThis tells us that the treatment — the inclusion of a matching donation offer — appears to influence the decision to donate, but not the amount given once someone has already made that decision. In other words, framing boosts participation, but not generosity.\n\n\n\n```{.r .cell-code}\n# donors only\ndonors_only <- match_data %>% filter(gave == 1)\ndonors_only$ratio <- factor(donors_only$ratio)\n```\n\nLinear Regression: amount ~ ratio (conditional on gave == 1)\n\n```\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 45.14286    2.76540 16.3242   <2e-16 ***\nratio2       0.19444    3.82852  0.0508   0.9595    \nratio3      -3.89108    3.82490 -1.0173   0.3093    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\nI ran a regression to examine whether the size of the match ratio influenced how much people donated, among those who chose to give. The results showed no statistically significant differences between the 1:1, 2:1, and 3:1 groups. Donors in the 2:1 group gave about 19 cents more than the 1:1 group, and donors in the 3:1 group gave about $3.89 less, but neither difference was meaningful or statistically reliable. However, this regression does not have a valid causal interpretation, since it only includes people who donated — a post-treatment outcome that breaks the randomization. As a result, we cannot conclude whether the match ratio itself caused any differences in donation amounts.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# treatment group histogram\ndonors_treat <- donors_only %>% filter(treatment == 1)\nmean_treat <- mean(donors_treat$amount, na.rm = TRUE)\nggplot(donors_treat, aes(x = amount)) +\n  geom_histogram(binwidth = 5, fill = \"skyblue\", color = \"white\") +\n  geom_vline(xintercept = mean_treat, color = \"red\", linetype = \"dashed\", size = 1) +\n  labs(\n    title = \"Donations Among Treatment Group (Gave == 1)\",\n    x = \"Donation Amount ($)\",\n    y = \"Number of Donors\"\n  ) +\n  annotate(\"text\", x = mean_treat, y = 5,\n           label = paste0(\"Mean = $\", round(mean_treat, 2)),\n           color = \"red\", vjust = -0.5) +\n  xlim(0, max(donors_treat$amount, na.rm = TRUE) + 10) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# regenerate control data\ndonors_only <- df %>% filter(gave == 1)  # from full df, not match_data\ndonors_control <- donors_only %>% filter(treatment == 0)\nmean_control <- mean(donors_control$amount, na.rm = TRUE)\n\n# control group histogram\nggplot(donors_control, aes(x = amount)) +\n  geom_histogram(binwidth = 5, fill = \"lightgreen\", color = \"white\") +\n  geom_vline(xintercept = mean_control, color = \"red\", linetype = \"dashed\", size = 1) +\n  labs(\n    title = \"Donations Among Control Group (Gave == 1)\",\n    x = \"Donation Amount ($)\",\n    y = \"Number of Donors\"\n  ) +\n  annotate(\"text\", x = mean_control, y = 5,\n           label = paste0(\"Mean = $\", round(mean_control, 2)),\n           color = \"red\", vjust = -0.5) +\n  xlim(0, max(donors_control$amount, na.rm = TRUE) + 10) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-2.png){width=672}\n:::\n:::\n\n\nWhile the treatment appears to have increased the number of people who gave (as shown earlier), these plots show that it did not meaningfully shift the amount donated among those who did give. Most donors gave similar amounts regardless of treatment status, reinforcing the idea that the matching offer influenced whether someone gave more than how much they gave.\n\n## Simulation Experiment\n\nAs a reminder of how the t-statistic \"works,\" in this section I use simulation to demonstrate the Law of Large Numbers and the Central Limit Theorem.\n\nSuppose the true distribution of respondents who do not get a charitable donation match is Bernoulli with probability p=0.018 that a donation is made. \n\nFurther suppose that the true distribution of respondents who do get a charitable donation match of any size  is Bernoulli with probability p=0.022 that a donation is made.\n\n### Law of Large Numbers\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set seed for reproducibility\nset.seed(42)\n\n# Simulate control group (Bernoulli with p = 0.018)\ncontrol_sim <- rbinom(n = 100000, size = 1, prob = 0.018)\n\n# Simulate treatment group (Bernoulli with p = 0.022)\ntreatment_sim <- rbinom(n = 10000, size = 1, prob = 0.022)\n\n# Calculate differences using first 10,000 control samples\ndiff_vector <- treatment_sim - control_sim[1:10000]\n\n# Cumulative average of differences\ncumulative_avg <- cumsum(diff_vector) / seq_along(diff_vector)\n\n# True difference\ntrue_diff <- 0.022 - 0.018\n\n# Plot\nplot(cumulative_avg, type = \"l\", col = \"blue\", lwd = 2,\n     main = \"Law of Large Numbers: Cumulative Avg of Bernoulli Differences\",\n     xlab = \"Number of Simulated Samples\",\n     ylab = \"Cumulative Average Difference\")\nabline(h = true_diff, col = \"red\", lty = 2)\nlegend(\"bottomright\", legend = paste0(\"True Difference = \", round(true_diff, 3)), \n       col = \"red\", lty = 2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nThis plot shows the cumulative average of differences in donation outcomes between the treatment and control groups, based on simulated data. I drew 10,000 values from the treatment group distribution and compared each to a randomly drawn value from the control group distribution. Each point on the blue line represents the average difference after one more simulated pair. As expected, the early differences are highly variable, but the line stabilizes as more data accumulate. The red dashed line represents the true difference in probabilities between the groups. The fact that the blue line converges to this value illustrates a key concept in statistics: with enough data, sampling variation averages out, and the sample-based estimate approaches the true effect.\n\n### Central Limit Theorem\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# Parameters\nsample_sizes <- c(50, 200, 500, 1000)\nsimulations <- 1000\np_control <- 0.018\np_treatment <- 0.022\nset.seed(42)\n\n# Function to simulate average differences\nsimulate_diff_dist <- function(n, reps = 1000) {\n  replicate(reps, {\n    control_draw <- rbinom(n, 1, p_control)\n    treatment_draw <- rbinom(n, 1, p_treatment)\n    mean(treatment_draw) - mean(control_draw)\n  })\n}\n\n# Plot results\npar(mfrow = c(2, 2))  # 2x2 grid\n\nfor (n in sample_sizes) {\n  diffs <- simulate_diff_dist(n)\n  hist(diffs,\n       breaks = 30,\n       main = paste(\"Sample Size =\", n),\n       xlab = \"Avg Treatment - Control\",\n       col = \"lightblue\",\n       border = \"white\")\n  abline(v = 0, col = \"red\", lwd = 2, lty = 2)\n}\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nThese histograms illustrate the distribution of simulated treatment effects—the average difference in donation rates between treatment and control groups—across varying sample sizes: 50, 200, 500, and 1000. In each plot, the red dashed line marks zero, representing the null hypothesis of no difference. At smaller sample sizes (n = 50 and 200), zero appears near the center of the distribution, indicating high variability and the possibility of observing no effect purely by chance. As the sample size increases (n = 500 and 1000), the distribution narrows, and zero shifts toward the tails. This suggests that with more data, estimates become more precise and it becomes less likely to observe a sample difference near zero if a true effect exists. These results demonstrate the Central Limit Theorem and highlight how larger samples improve our ability to detect real treatment effects and reject the null hypothesis when appropriate.\n\n\n\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}